spring.application.name=service-autenticacion
server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/bd_seguridad
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate

#Llave secreta para firmar el Token (minimo 32 caracteres)
jwt.secret=856K34jfh234tmA324pktB98702ghA2h
# PARA APAGAR EL BLOQUEO
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration