spring.application.name=service-autenticacion
server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/bd_seguridad
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate

#Llave secreta para firmar el Token (minimo 32 caracteres)
jwt.secret=856K34jfh234tmA324pktB98702ghA2h

# Mueve la ruta del JSON de Swagger dentro de /auth
springdoc.api-docs.path=/auth/v3/api-docs

# Mueve la interfaz gráfica de Swagger dentro de /auth
springdoc.swagger-ui.path=/auth/swagger-ui.html
