spring.application.name=service-reportes
server.port=8088
#Conexion a BD Reportes
spring.datasource.url=jdbc:mysql://localhost:3306/bd_reportes?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true