spring.application.name=service-logistica
server.port = 8085
#Conexion a BD Logistica
spring.datasource.url=jdbc:mysql://localhost:3306/bd_logistica?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true